### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by angel-baal** [langmansh/AKStreamWebUI#3]
tor.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at YiSha.Data.EF.MySqlDatabase.CommitTrans() in /root/AKStreamWebUI/YiSha.Data/YiSha.Data.EF/Database/MySqlDatabase.cs:line 65
   at YiSha.Data.EF.MySqlDatabase.CommitTrans() in /root/AKStreamWebUI/YiSha.Data/YiSha.Data.EF/Database/MySqlDatabase.cs:line 87
   at YiSha.Data.EF.MySqlDatabase.Insert[T](T entity) in /root/AKStreamWebUI/YiSha.Data/YiSha.Data.EF/Database/MySqlDatabase.cs:line 162
   at YiSha.Data.Repository.Repository.Insert[T](T entity) in /root/AKStreamWebUI/YiSha.Data/YiSha.Data.Repository/Repository.cs:line 69
   at YiSha.Service.SystemManage.LogOperateService.SaveForm(LogOperateEntity entity) in /root/AKStreamWebUI/YiSha.Business/YiSha.Service/SystemManage/LogOperateService.cs:line 50
   at YiSha.Business.SystemManage.LogOperateBLL.SaveForm(LogOperateEntity entity) in /root/AKStreamWebUI/YiSha.Business/YiSha.Business/SystemManage/LogOperateBLL.cs:line 66
   at YiSha.Admin.Web.Controllers.BaseController.<>c__DisplayClass0_0.<<OnActionExecutionAsync>b__2>d.MoveNext() in /root/AKStreamWebUI/YiSha.Web/YiSha.Admin.Web/bin/Controllers/BaseController.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
已放

**Comment by angel-baal** [comment]
Content root path: /root/AKStreamWebUI/YiSha.Web/YiSha.Admin.Web/bin/Debug/netcoreapp3.1
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
Unhandled exception.Unhandled exception.  Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'yishaadmin.SysLogOperate' doesn't exist
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'yishaadmin.SysLogOperate' doesn't exist
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 774

**Comment by langmansh** [comment]
数据库的问题 检查下数据库的组件是不是还原了 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;angel-baal&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月1日(星期一) 下午4:31
收件人:&nbsp;&quot;langmansh/AKStreamWebUI&quot;<AKStreamWebUI@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[langmansh/AKStreamWebUI] 启动报错 (#3)

**Comment by langmansh** [comment]
数据库所需要的组件还原了的话 检查下表名'yishaadmin.SysLogOperate' 看看是不是区分了大小写------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;angel-baal&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月1日(星期一) 下午4:32
收件人:&nbsp;&quot;langmansh/AKStreamWebUI&quot;<AKStreamWebUI@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [langmansh/AKStreamWebUI] 启动报错 (#3)
